### ISSUE TITLE
Tool Tips need to be readable when on right edge of screen

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#141]
Tool tips that pop up on the far right side of the screen can be unreadable. Can these pop up to the left of the field of concern? Here is an examplel

![Image](https://user-images.githubusercontent.com/11503959/223159932-51daf57b-b7fe-45c3-816f-85ab0423fa21.png)

**Comment by desais-jax** [comment]
@belkassaby This is still happening. I create a phenopacket. Then I went to dashboard and and selected a phenopacket . The tooltip text is split. We need to wrap it. Please see screenshot below. 


![Image](https://user-images.githubusercontent.com/72874793/236839639-29e5ed23-7d38-46a3-9e15-74fbd190e737.png)

**Comment by belkassaby** [comment]
in the branch im working on, all of these are fixed

**Comment by BethSundberg** [comment]
@belkassaby I still see this problem. Let me know when the branch with the fix is available for SQA. 

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/52997529-c42d-4d28-b836-bd10a00c5346)

**Comment by BethSundberg** [comment]
@belkassaby I am still finding tool tips that are not readable. Moving this back to in progress.


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/199adc99-8b1d-4a44-8dbf-eea93f55196c)

**Comment by BethSundberg** [comment]
@belkassaby I still see the problem described above, where the tool tip is sometimes off on the right and sometimes it is okay.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/6490c516-4572-4aac-89c6-5bc2849b2a00)

**Comment by belkassaby** [comment]
Ive just committed a change to put this particular one on the left (it was set in the code at the bottom, but due to bad positioning, it would wrap the text unecessarily

**Comment by BethSundberg** [comment]
These tool tips have been fixed.
